// className types for core RN components are generated by Uniwind's Metro
// transform into ./uniwind-types.d.ts (see metro.config.js). This file just
// allows the side-effect import of the CSS entry in app/_layout.tsx.
declare module "*.css";
